#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVLCmanage
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Soudvilay")]
	public partial class SouvilayDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertsubject(subject instance);
    partial void Updatesubject(subject instance);
    partial void Deletesubject(subject instance);
    partial void Insertauth(auth instance);
    partial void Updateauth(auth instance);
    partial void Deleteauth(auth instance);
    partial void Insertcost(cost instance);
    partial void Updatecost(cost instance);
    partial void Deletecost(cost instance);
    partial void Insertgrade(grade instance);
    partial void Updategrade(grade instance);
    partial void Deletegrade(grade instance);
    partial void Insertlogin(login instance);
    partial void Updatelogin(login instance);
    partial void Deletelogin(login instance);
    partial void Insertstudent(student instance);
    partial void Updatestudent(student instance);
    partial void Deletestudent(student instance);
    #endregion
		
		public SouvilayDataClassesDataContext() : 
				base(global::SVLCmanage.Properties.Settings.Default.SoudvilayConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SouvilayDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SouvilayDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SouvilayDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SouvilayDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<subject> subjects
		{
			get
			{
				return this.GetTable<subject>();
			}
		}
		
		public System.Data.Linq.Table<auth> auths
		{
			get
			{
				return this.GetTable<auth>();
			}
		}
		
		public System.Data.Linq.Table<cost> costs
		{
			get
			{
				return this.GetTable<cost>();
			}
		}
		
		public System.Data.Linq.Table<grade> grades
		{
			get
			{
				return this.GetTable<grade>();
			}
		}
		
		public System.Data.Linq.Table<login> logins
		{
			get
			{
				return this.GetTable<login>();
			}
		}
		
		public System.Data.Linq.Table<student> students
		{
			get
			{
				return this.GetTable<student>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.subject")]
	public partial class subject : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _subject_id;
		
		private string _subject_name;
		
		private string _subject_engname;
		
		private System.Nullable<int> _subject_credit;
		
		private string _subject_hour;
		
		private string _degree12plus4;
		
		private string _degree11plus3plus3;
		
		private string _degree12plus3;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsubject_idChanging(string value);
    partial void Onsubject_idChanged();
    partial void Onsubject_nameChanging(string value);
    partial void Onsubject_nameChanged();
    partial void Onsubject_engnameChanging(string value);
    partial void Onsubject_engnameChanged();
    partial void Onsubject_creditChanging(System.Nullable<int> value);
    partial void Onsubject_creditChanged();
    partial void Onsubject_hourChanging(string value);
    partial void Onsubject_hourChanged();
    partial void Ondegree12plus4Changing(string value);
    partial void Ondegree12plus4Changed();
    partial void Ondegree11plus3plus3Changing(string value);
    partial void Ondegree11plus3plus3Changed();
    partial void Ondegree12plus3Changing(string value);
    partial void Ondegree12plus3Changed();
    #endregion
		
		public subject()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string subject_id
		{
			get
			{
				return this._subject_id;
			}
			set
			{
				if ((this._subject_id != value))
				{
					this.Onsubject_idChanging(value);
					this.SendPropertyChanging();
					this._subject_id = value;
					this.SendPropertyChanged("subject_id");
					this.Onsubject_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject_name", DbType="NVarChar(50)")]
		public string subject_name
		{
			get
			{
				return this._subject_name;
			}
			set
			{
				if ((this._subject_name != value))
				{
					this.Onsubject_nameChanging(value);
					this.SendPropertyChanging();
					this._subject_name = value;
					this.SendPropertyChanged("subject_name");
					this.Onsubject_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject_engname", DbType="NVarChar(50)")]
		public string subject_engname
		{
			get
			{
				return this._subject_engname;
			}
			set
			{
				if ((this._subject_engname != value))
				{
					this.Onsubject_engnameChanging(value);
					this.SendPropertyChanging();
					this._subject_engname = value;
					this.SendPropertyChanged("subject_engname");
					this.Onsubject_engnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject_credit", DbType="Int")]
		public System.Nullable<int> subject_credit
		{
			get
			{
				return this._subject_credit;
			}
			set
			{
				if ((this._subject_credit != value))
				{
					this.Onsubject_creditChanging(value);
					this.SendPropertyChanging();
					this._subject_credit = value;
					this.SendPropertyChanged("subject_credit");
					this.Onsubject_creditChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject_hour", DbType="NVarChar(50)")]
		public string subject_hour
		{
			get
			{
				return this._subject_hour;
			}
			set
			{
				if ((this._subject_hour != value))
				{
					this.Onsubject_hourChanging(value);
					this.SendPropertyChanging();
					this._subject_hour = value;
					this.SendPropertyChanged("subject_hour");
					this.Onsubject_hourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_degree12plus4", DbType="NVarChar(50)")]
		public string degree12plus4
		{
			get
			{
				return this._degree12plus4;
			}
			set
			{
				if ((this._degree12plus4 != value))
				{
					this.Ondegree12plus4Changing(value);
					this.SendPropertyChanging();
					this._degree12plus4 = value;
					this.SendPropertyChanged("degree12plus4");
					this.Ondegree12plus4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_degree11plus3plus3", DbType="NVarChar(50)")]
		public string degree11plus3plus3
		{
			get
			{
				return this._degree11plus3plus3;
			}
			set
			{
				if ((this._degree11plus3plus3 != value))
				{
					this.Ondegree11plus3plus3Changing(value);
					this.SendPropertyChanging();
					this._degree11plus3plus3 = value;
					this.SendPropertyChanged("degree11plus3plus3");
					this.Ondegree11plus3plus3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_degree12plus3", DbType="NVarChar(50)")]
		public string degree12plus3
		{
			get
			{
				return this._degree12plus3;
			}
			set
			{
				if ((this._degree12plus3 != value))
				{
					this.Ondegree12plus3Changing(value);
					this.SendPropertyChanging();
					this._degree12plus3 = value;
					this.SendPropertyChanged("degree12plus3");
					this.Ondegree12plus3Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.auth")]
	public partial class auth : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _user_id;
		
		private string _user_pass;
		
		private string _user_auth;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(string value);
    partial void Onuser_idChanged();
    partial void Onuser_passChanging(string value);
    partial void Onuser_passChanged();
    partial void Onuser_authChanging(string value);
    partial void Onuser_authChanged();
    #endregion
		
		public auth()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_pass", DbType="NVarChar(50)")]
		public string user_pass
		{
			get
			{
				return this._user_pass;
			}
			set
			{
				if ((this._user_pass != value))
				{
					this.Onuser_passChanging(value);
					this.SendPropertyChanging();
					this._user_pass = value;
					this.SendPropertyChanged("user_pass");
					this.Onuser_passChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_auth", DbType="NVarChar(50)")]
		public string user_auth
		{
			get
			{
				return this._user_auth;
			}
			set
			{
				if ((this._user_auth != value))
				{
					this.Onuser_authChanging(value);
					this.SendPropertyChanging();
					this._user_auth = value;
					this.SendPropertyChanged("user_auth");
					this.Onuser_authChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cost")]
	public partial class cost : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _index;
		
		private string _student_name;
		
		private string _term1;
		
		private string _term2;
		
		private string _term3;
		
		private string _term4;
		
		private string _term5;
		
		private string _term6;
		
		private string _term7;
		
		private string _term8;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnindexChanging(int value);
    partial void OnindexChanged();
    partial void Onstudent_nameChanging(string value);
    partial void Onstudent_nameChanged();
    partial void Onterm1Changing(string value);
    partial void Onterm1Changed();
    partial void Onterm2Changing(string value);
    partial void Onterm2Changed();
    partial void Onterm3Changing(string value);
    partial void Onterm3Changed();
    partial void Onterm4Changing(string value);
    partial void Onterm4Changed();
    partial void Onterm5Changing(string value);
    partial void Onterm5Changed();
    partial void Onterm6Changing(string value);
    partial void Onterm6Changed();
    partial void Onterm7Changing(string value);
    partial void Onterm7Changed();
    partial void Onterm8Changing(string value);
    partial void Onterm8Changed();
    #endregion
		
		public cost()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[index]", Storage="_index", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int index
		{
			get
			{
				return this._index;
			}
			set
			{
				if ((this._index != value))
				{
					this.OnindexChanging(value);
					this.SendPropertyChanging();
					this._index = value;
					this.SendPropertyChanged("index");
					this.OnindexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_name", DbType="NVarChar(50)")]
		public string student_name
		{
			get
			{
				return this._student_name;
			}
			set
			{
				if ((this._student_name != value))
				{
					this.Onstudent_nameChanging(value);
					this.SendPropertyChanging();
					this._student_name = value;
					this.SendPropertyChanged("student_name");
					this.Onstudent_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_term1", DbType="NVarChar(50)")]
		public string term1
		{
			get
			{
				return this._term1;
			}
			set
			{
				if ((this._term1 != value))
				{
					this.Onterm1Changing(value);
					this.SendPropertyChanging();
					this._term1 = value;
					this.SendPropertyChanged("term1");
					this.Onterm1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_term2", DbType="NVarChar(50)")]
		public string term2
		{
			get
			{
				return this._term2;
			}
			set
			{
				if ((this._term2 != value))
				{
					this.Onterm2Changing(value);
					this.SendPropertyChanging();
					this._term2 = value;
					this.SendPropertyChanged("term2");
					this.Onterm2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_term3", DbType="NVarChar(50)")]
		public string term3
		{
			get
			{
				return this._term3;
			}
			set
			{
				if ((this._term3 != value))
				{
					this.Onterm3Changing(value);
					this.SendPropertyChanging();
					this._term3 = value;
					this.SendPropertyChanged("term3");
					this.Onterm3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_term4", DbType="NVarChar(50)")]
		public string term4
		{
			get
			{
				return this._term4;
			}
			set
			{
				if ((this._term4 != value))
				{
					this.Onterm4Changing(value);
					this.SendPropertyChanging();
					this._term4 = value;
					this.SendPropertyChanged("term4");
					this.Onterm4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_term5", DbType="NVarChar(50)")]
		public string term5
		{
			get
			{
				return this._term5;
			}
			set
			{
				if ((this._term5 != value))
				{
					this.Onterm5Changing(value);
					this.SendPropertyChanging();
					this._term5 = value;
					this.SendPropertyChanged("term5");
					this.Onterm5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_term6", DbType="NVarChar(50)")]
		public string term6
		{
			get
			{
				return this._term6;
			}
			set
			{
				if ((this._term6 != value))
				{
					this.Onterm6Changing(value);
					this.SendPropertyChanging();
					this._term6 = value;
					this.SendPropertyChanged("term6");
					this.Onterm6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_term7", DbType="NVarChar(50)")]
		public string term7
		{
			get
			{
				return this._term7;
			}
			set
			{
				if ((this._term7 != value))
				{
					this.Onterm7Changing(value);
					this.SendPropertyChanging();
					this._term7 = value;
					this.SendPropertyChanged("term7");
					this.Onterm7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_term8", DbType="NVarChar(50)")]
		public string term8
		{
			get
			{
				return this._term8;
			}
			set
			{
				if ((this._term8 != value))
				{
					this.Onterm8Changing(value);
					this.SendPropertyChanging();
					this._term8 = value;
					this.SendPropertyChanged("term8");
					this.Onterm8Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.grade")]
	public partial class grade : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _index;
		
		private string _student_id;
		
		private string _subject_id;
		
		private string _teacher_name;
		
		private string _grade_total;
		
		private string _grade_grade;
		
		private System.Nullable<decimal> _grade_average;
		
		private string _subject_tyear;
		
		private string _grade_typer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnindexChanging(int value);
    partial void OnindexChanged();
    partial void Onstudent_idChanging(string value);
    partial void Onstudent_idChanged();
    partial void Onsubject_idChanging(string value);
    partial void Onsubject_idChanged();
    partial void Onteacher_nameChanging(string value);
    partial void Onteacher_nameChanged();
    partial void Ongrade_totalChanging(string value);
    partial void Ongrade_totalChanged();
    partial void Ongrade_gradeChanging(string value);
    partial void Ongrade_gradeChanged();
    partial void Ongrade_averageChanging(System.Nullable<decimal> value);
    partial void Ongrade_averageChanged();
    partial void Onsubject_tyearChanging(string value);
    partial void Onsubject_tyearChanged();
    partial void Ongrade_typerChanging(string value);
    partial void Ongrade_typerChanged();
    #endregion
		
		public grade()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[index]", Storage="_index", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int index
		{
			get
			{
				return this._index;
			}
			set
			{
				if ((this._index != value))
				{
					this.OnindexChanging(value);
					this.SendPropertyChanging();
					this._index = value;
					this.SendPropertyChanged("index");
					this.OnindexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_id", DbType="NVarChar(50)")]
		public string student_id
		{
			get
			{
				return this._student_id;
			}
			set
			{
				if ((this._student_id != value))
				{
					this.Onstudent_idChanging(value);
					this.SendPropertyChanging();
					this._student_id = value;
					this.SendPropertyChanged("student_id");
					this.Onstudent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject_id", DbType="NVarChar(50)")]
		public string subject_id
		{
			get
			{
				return this._subject_id;
			}
			set
			{
				if ((this._subject_id != value))
				{
					this.Onsubject_idChanging(value);
					this.SendPropertyChanging();
					this._subject_id = value;
					this.SendPropertyChanged("subject_id");
					this.Onsubject_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teacher_name", DbType="NVarChar(50)")]
		public string teacher_name
		{
			get
			{
				return this._teacher_name;
			}
			set
			{
				if ((this._teacher_name != value))
				{
					this.Onteacher_nameChanging(value);
					this.SendPropertyChanging();
					this._teacher_name = value;
					this.SendPropertyChanged("teacher_name");
					this.Onteacher_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grade_total", DbType="NVarChar(50)")]
		public string grade_total
		{
			get
			{
				return this._grade_total;
			}
			set
			{
				if ((this._grade_total != value))
				{
					this.Ongrade_totalChanging(value);
					this.SendPropertyChanging();
					this._grade_total = value;
					this.SendPropertyChanged("grade_total");
					this.Ongrade_totalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grade_grade", DbType="NVarChar(50)")]
		public string grade_grade
		{
			get
			{
				return this._grade_grade;
			}
			set
			{
				if ((this._grade_grade != value))
				{
					this.Ongrade_gradeChanging(value);
					this.SendPropertyChanging();
					this._grade_grade = value;
					this.SendPropertyChanged("grade_grade");
					this.Ongrade_gradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grade_average", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> grade_average
		{
			get
			{
				return this._grade_average;
			}
			set
			{
				if ((this._grade_average != value))
				{
					this.Ongrade_averageChanging(value);
					this.SendPropertyChanging();
					this._grade_average = value;
					this.SendPropertyChanged("grade_average");
					this.Ongrade_averageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject_tyear", DbType="NVarChar(50)")]
		public string subject_tyear
		{
			get
			{
				return this._subject_tyear;
			}
			set
			{
				if ((this._subject_tyear != value))
				{
					this.Onsubject_tyearChanging(value);
					this.SendPropertyChanging();
					this._subject_tyear = value;
					this.SendPropertyChanged("subject_tyear");
					this.Onsubject_tyearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grade_typer", DbType="NVarChar(50)")]
		public string grade_typer
		{
			get
			{
				return this._grade_typer;
			}
			set
			{
				if ((this._grade_typer != value))
				{
					this.Ongrade_typerChanging(value);
					this.SendPropertyChanging();
					this._grade_typer = value;
					this.SendPropertyChanged("grade_typer");
					this.Ongrade_typerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.login")]
	public partial class login : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _index;
		
		private string _username_ip;
		
		private string _logintime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnindexChanging(int value);
    partial void OnindexChanged();
    partial void Onusername_ipChanging(string value);
    partial void Onusername_ipChanged();
    partial void OnlogintimeChanging(string value);
    partial void OnlogintimeChanged();
    #endregion
		
		public login()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[index]", Storage="_index", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int index
		{
			get
			{
				return this._index;
			}
			set
			{
				if ((this._index != value))
				{
					this.OnindexChanging(value);
					this.SendPropertyChanging();
					this._index = value;
					this.SendPropertyChanged("index");
					this.OnindexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username_ip", DbType="NVarChar(50)")]
		public string username_ip
		{
			get
			{
				return this._username_ip;
			}
			set
			{
				if ((this._username_ip != value))
				{
					this.Onusername_ipChanging(value);
					this.SendPropertyChanging();
					this._username_ip = value;
					this.SendPropertyChanged("username_ip");
					this.Onusername_ipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logintime", DbType="NVarChar(50)")]
		public string logintime
		{
			get
			{
				return this._logintime;
			}
			set
			{
				if ((this._logintime != value))
				{
					this.OnlogintimeChanging(value);
					this.SendPropertyChanging();
					this._logintime = value;
					this.SendPropertyChanged("logintime");
					this.OnlogintimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.student")]
	public partial class student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _student_id;
		
		private string _student_name;
		
		private string _student_engname;
		
		private string _student_gender;
		
		private string _student_birthday;
		
		private string _student_addressbirth;
		
		private string _student_address;
		
		private string _student_tel;
		
		private string _student_degree;
		
		private string _student_department;
		
		private string _student_major;
		
		private string _student_timestudy;
		
		private string _student_year;
		
		private string _student_yearend;
		
		private string _student_info;
		
		private System.Data.Linq.Binary _student_pic;
		
		private string _student_classroom;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onstudent_idChanging(int value);
    partial void Onstudent_idChanged();
    partial void Onstudent_nameChanging(string value);
    partial void Onstudent_nameChanged();
    partial void Onstudent_engnameChanging(string value);
    partial void Onstudent_engnameChanged();
    partial void Onstudent_genderChanging(string value);
    partial void Onstudent_genderChanged();
    partial void Onstudent_birthdayChanging(string value);
    partial void Onstudent_birthdayChanged();
    partial void Onstudent_addressbirthChanging(string value);
    partial void Onstudent_addressbirthChanged();
    partial void Onstudent_addressChanging(string value);
    partial void Onstudent_addressChanged();
    partial void Onstudent_telChanging(string value);
    partial void Onstudent_telChanged();
    partial void Onstudent_degreeChanging(string value);
    partial void Onstudent_degreeChanged();
    partial void Onstudent_departmentChanging(string value);
    partial void Onstudent_departmentChanged();
    partial void Onstudent_majorChanging(string value);
    partial void Onstudent_majorChanged();
    partial void Onstudent_timestudyChanging(string value);
    partial void Onstudent_timestudyChanged();
    partial void Onstudent_yearChanging(string value);
    partial void Onstudent_yearChanged();
    partial void Onstudent_yearendChanging(string value);
    partial void Onstudent_yearendChanged();
    partial void Onstudent_infoChanging(string value);
    partial void Onstudent_infoChanged();
    partial void Onstudent_picChanging(System.Data.Linq.Binary value);
    partial void Onstudent_picChanged();
    partial void Onstudent_classroomChanging(string value);
    partial void Onstudent_classroomChanged();
    #endregion
		
		public student()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int student_id
		{
			get
			{
				return this._student_id;
			}
			set
			{
				if ((this._student_id != value))
				{
					this.Onstudent_idChanging(value);
					this.SendPropertyChanging();
					this._student_id = value;
					this.SendPropertyChanged("student_id");
					this.Onstudent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_name", DbType="NVarChar(50)")]
		public string student_name
		{
			get
			{
				return this._student_name;
			}
			set
			{
				if ((this._student_name != value))
				{
					this.Onstudent_nameChanging(value);
					this.SendPropertyChanging();
					this._student_name = value;
					this.SendPropertyChanged("student_name");
					this.Onstudent_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_engname", DbType="NVarChar(50)")]
		public string student_engname
		{
			get
			{
				return this._student_engname;
			}
			set
			{
				if ((this._student_engname != value))
				{
					this.Onstudent_engnameChanging(value);
					this.SendPropertyChanging();
					this._student_engname = value;
					this.SendPropertyChanged("student_engname");
					this.Onstudent_engnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_gender", DbType="NVarChar(50)")]
		public string student_gender
		{
			get
			{
				return this._student_gender;
			}
			set
			{
				if ((this._student_gender != value))
				{
					this.Onstudent_genderChanging(value);
					this.SendPropertyChanging();
					this._student_gender = value;
					this.SendPropertyChanged("student_gender");
					this.Onstudent_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_birthday", DbType="NVarChar(50)")]
		public string student_birthday
		{
			get
			{
				return this._student_birthday;
			}
			set
			{
				if ((this._student_birthday != value))
				{
					this.Onstudent_birthdayChanging(value);
					this.SendPropertyChanging();
					this._student_birthday = value;
					this.SendPropertyChanged("student_birthday");
					this.Onstudent_birthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_addressbirth", DbType="NVarChar(50)")]
		public string student_addressbirth
		{
			get
			{
				return this._student_addressbirth;
			}
			set
			{
				if ((this._student_addressbirth != value))
				{
					this.Onstudent_addressbirthChanging(value);
					this.SendPropertyChanging();
					this._student_addressbirth = value;
					this.SendPropertyChanged("student_addressbirth");
					this.Onstudent_addressbirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_address", DbType="NVarChar(50)")]
		public string student_address
		{
			get
			{
				return this._student_address;
			}
			set
			{
				if ((this._student_address != value))
				{
					this.Onstudent_addressChanging(value);
					this.SendPropertyChanging();
					this._student_address = value;
					this.SendPropertyChanged("student_address");
					this.Onstudent_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_tel", DbType="NVarChar(50)")]
		public string student_tel
		{
			get
			{
				return this._student_tel;
			}
			set
			{
				if ((this._student_tel != value))
				{
					this.Onstudent_telChanging(value);
					this.SendPropertyChanging();
					this._student_tel = value;
					this.SendPropertyChanged("student_tel");
					this.Onstudent_telChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_degree", DbType="NVarChar(50)")]
		public string student_degree
		{
			get
			{
				return this._student_degree;
			}
			set
			{
				if ((this._student_degree != value))
				{
					this.Onstudent_degreeChanging(value);
					this.SendPropertyChanging();
					this._student_degree = value;
					this.SendPropertyChanged("student_degree");
					this.Onstudent_degreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_department", DbType="NVarChar(50)")]
		public string student_department
		{
			get
			{
				return this._student_department;
			}
			set
			{
				if ((this._student_department != value))
				{
					this.Onstudent_departmentChanging(value);
					this.SendPropertyChanging();
					this._student_department = value;
					this.SendPropertyChanged("student_department");
					this.Onstudent_departmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_major", DbType="NVarChar(50)")]
		public string student_major
		{
			get
			{
				return this._student_major;
			}
			set
			{
				if ((this._student_major != value))
				{
					this.Onstudent_majorChanging(value);
					this.SendPropertyChanging();
					this._student_major = value;
					this.SendPropertyChanged("student_major");
					this.Onstudent_majorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_timestudy", DbType="NVarChar(50)")]
		public string student_timestudy
		{
			get
			{
				return this._student_timestudy;
			}
			set
			{
				if ((this._student_timestudy != value))
				{
					this.Onstudent_timestudyChanging(value);
					this.SendPropertyChanging();
					this._student_timestudy = value;
					this.SendPropertyChanged("student_timestudy");
					this.Onstudent_timestudyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_year", DbType="NVarChar(50)")]
		public string student_year
		{
			get
			{
				return this._student_year;
			}
			set
			{
				if ((this._student_year != value))
				{
					this.Onstudent_yearChanging(value);
					this.SendPropertyChanging();
					this._student_year = value;
					this.SendPropertyChanged("student_year");
					this.Onstudent_yearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_yearend", DbType="NVarChar(50)")]
		public string student_yearend
		{
			get
			{
				return this._student_yearend;
			}
			set
			{
				if ((this._student_yearend != value))
				{
					this.Onstudent_yearendChanging(value);
					this.SendPropertyChanging();
					this._student_yearend = value;
					this.SendPropertyChanged("student_yearend");
					this.Onstudent_yearendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_info", DbType="NVarChar(50)")]
		public string student_info
		{
			get
			{
				return this._student_info;
			}
			set
			{
				if ((this._student_info != value))
				{
					this.Onstudent_infoChanging(value);
					this.SendPropertyChanging();
					this._student_info = value;
					this.SendPropertyChanged("student_info");
					this.Onstudent_infoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_pic", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary student_pic
		{
			get
			{
				return this._student_pic;
			}
			set
			{
				if ((this._student_pic != value))
				{
					this.Onstudent_picChanging(value);
					this.SendPropertyChanging();
					this._student_pic = value;
					this.SendPropertyChanged("student_pic");
					this.Onstudent_picChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_classroom", DbType="NVarChar(50)")]
		public string student_classroom
		{
			get
			{
				return this._student_classroom;
			}
			set
			{
				if ((this._student_classroom != value))
				{
					this.Onstudent_classroomChanging(value);
					this.SendPropertyChanging();
					this._student_classroom = value;
					this.SendPropertyChanged("student_classroom");
					this.Onstudent_classroomChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
